### ISSUE TITLE
module 'jax.random' has no attribute 'KeyArray'

### ISSUE THREAD

**Issue by VinaySingh561** [jax-md/jax-md#324]
Hi,
I have tried multiple combinations of Jax, jaxlib and jax_md versions, but every time, I get the following error.
Please help me out in resolving this issue. Thank you for your time and consideration.
Detailed error  : 
AttributeError                            Traceback (most recent call last)
[<ipython-input-4-209704c03c8d>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from jax_md import space

2 frames
[/usr/local/lib/python3.10/dist-packages/jax_md/__init__.py](https://localhost:8080/#) in <module>
     25 from jax_md import util
     26 from jax_md import io
---> 27 from jax_md import rigid_body
     28 
     29 try:

[/usr/local/lib/python3.10/dist-packages/jax_md/rigid_body.py](https://localhost:8080/#) in <module>
     74 f64 = util.f64
     75 f32 = util.f32
---> 76 KeyArray = random.KeyArray
     77 NeighborListFns = partition.NeighborListFns
     78 ShiftFn = space.ShiftFn

[/usr/local/lib/python3.10/dist-packages/jax/_src/deprecations.py](https://localhost:8080/#) in getattr(name)
     53       warnings.warn(message, DeprecationWarning, stacklevel=2)
     54       return fn
---> 55     raise AttributeError(f"module {module!r} has no attribute {name!r}")
     56 
     57   return getattr

AttributeError: module 'jax.random' has no attribute 'KeyArray'

**Comment by alejandrosantanabonilla** [comment]
I am also experiencing the same error. This is my pip list:

absl-py             2.1.0
attrs               24.2.0
chex                0.1.87
contextlib2         21.6.0
dataclasses         0.6
dm-haiku            0.0.12
e3nn-jax            0.20.7
einops              0.8.0
etils               1.9.4
flax                0.9.0
fsspec              2024.9.0
humanize            4.11.0
importlib_resources 6.4.5
jax                 0.4.34
jax-md              0.2.8
jaxlib              0.4.34
jmp                 0.0.4
jraph               0.0.6.dev0
markdown-it-py      3.0.0
mdurl               0.1.2
ml_collections      0.1.1
ml_dtypes           0.5.0
mpmath              1.3.0
msgpack             1.1.0
nest-asyncio        1.6.0
numpy               2.1.2
opt_einsum          3.4.0
optax               0.2.3
orbax-checkpoint    0.7.0
pip                 22.0.2
protobuf            5.28.2
Pygments            2.18.0
PyYAML              6.0.2
rich                13.9.2
scipy               1.14.1
setuptools          59.6.0
six                 1.16.0
sympy               1.13.3
tabulate            0.9.0
tensorstore         0.1.66
toolz               1.0.0
typing_extensions   4.12.2
zipp                3.20.2


and this is the error:
Traceback (most recent call last):
  File "/home/alejandro/Documents/MD_jax_HP_model/example.py", line 3, in <module>
    import jax_md as jmd
  File "/home/alejandro/Documents/MD_jax_HP_model/md/lib/python3.10/site-packages/jax_md/__init__.py", line 27, in <module>
    from jax_md import rigid_body
  File "/home/alejandro/Documents/MD_jax_HP_model/md/lib/python3.10/site-packages/jax_md/rigid_body.py", line 76, in <module>
    KeyArray = random.KeyArray
  File "/home/alejandro/Documents/MD_jax_HP_model/md/lib/python3.10/site-packages/jax/_src/deprecations.py", line 55, in getattr
    raise AttributeError(f"module {module!r} has no attribute {name!r}")
AttributeError: module 'jax.random' has no attribute 'KeyArray'

Is it possible to get a solution by changing Jax version or how can I solve the problem? thanks in advance

**Comment by VinaySingh561** [comment]
Thanks, it worked.
